version: '3.8'
services:
  user:
    build:
      context: ./Userservice
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - NODE_ENV=production
    labels:
      -  traefik.enable=true
      -  traefik.http.routers.users-http.rule=Host(`localhost`) && PathPrefix(`/users`)
      -  traefik.http.routers.users-http.entrypoints=web

  sql:
    build:
      context: ./WebBossModellerSqlGenerator
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - NODE_ENV=production
    depends_on:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.sql-http.rule=Host(`localhost`) && PathPrefix(`/sql`)
      - traefik.http.routers.sql-http.entrypoints=web
      #-  "traefik.http.routers.user.rule=Host(`app`) && PathPrefix(`sql`)"
  traefik: #reverse proxy
    image: traefik:v3.2
    command:  --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "82:82"
      # The Web UI (enabled by --api.insecure=true)
      - "8082:8082"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro