on:
  push:
    branches:
      - deployment
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Transfer repository to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}:12000
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "."
          target: ${{ secrets.WORK_DIR }}
